'use client';
import {motion,useMotionValue,useSpring} from 'framer-motion';
import {useRef,useEffect} from 'react';
import Link from 'next/link';
import {useStudioMotion} from './StudioShell';
export function Reveal({children,className='',delay=0}:{children:React.ReactNode;className?:string;delay?:number}){return <motion.div className={className} initial={{opacity:0,y:45}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.12}} transition={{duration:.75,delay,ease:[.22,1,.36,1]}}>{children}</motion.div>}
export function ArrowButton({href,children,light=false}:{href:string;children:React.ReactNode;light?:boolean}){return <Link href={href} className={`arrow-button ${light?'light':''}`}><span>{children}</span><b aria-hidden>↗</b></Link>}
export function Tilt({children,className=''}:{children:React.ReactNode;className?:string}){const enabled=useStudioMotion();const x=useMotionValue(0),y=useMotionValue(0);const sx=useSpring(x,{stiffness:150,damping:20}),sy=useSpring(y,{stiffness:150,damping:20});return <motion.div className={className} style={{rotateX:sx,rotateY:sy,transformPerspective:1200}} onPointerMove={e=>{if(!enabled||e.pointerType==='touch')return;const b=e.currentTarget.getBoundingClientRect();x.set(-(e.clientY-b.top-b.height/2)/b.height*10);y.set((e.clientX-b.left-b.width/2)/b.width*10)}} onPointerLeave={()=>{x.set(0);y.set(0)}}>{children}</motion.div>}
export function ProjectVideo({src,poster,className=''}:{src:string;poster:string;className?:string}){const video=useRef<HTMLVideoElement>(null);const enabled=useStudioMotion();useEffect(()=>{const el=video.current;if(!el)return;if(!enabled){el.pause();el.currentTime=0;return}const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting)el.play().catch(()=>{});else el.pause()},{threshold:.15});observer.observe(el);return()=>observer.disconnect()},[enabled]);return <video ref={video} className={className} src={src} poster={poster} muted loop playsInline preload="none" aria-hidden/>}
export function Marquee(){return <div className="marquee" aria-label="Good thinking. Great design. A little undo. A lot of possibility."><div aria-hidden>{Array.from({length:4},(_,i)=><span key={i}>GOOD THINKING <i>✳</i> GREAT DESIGN <i>✳</i> A LITTLE UNDO <i>✳</i> A LOT OF POSSIBILITY <i>✳</i></span>)}</div></div>}
