'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {createContext,useContext,useEffect,useState,useRef} from 'react';
import {AnimatePresence,motion,MotionConfig} from 'framer-motion';
import Lenis from 'lenis';
const MotionContext=createContext(true);
export const useStudioMotion=()=>useContext(MotionContext);
export function Wordmark(){return <span className="wordmark"><small>STUDIO</small><span>undo<span className="logo-slash">/</span>redo<span className="logo-dot" aria-hidden>●</span></span></span>}
export default function StudioShell({children}:{children:React.ReactNode}){
 const pathname=usePathname();const[open,setOpen]=useState(false);const[loading,setLoading]=useState(true);const[animated,setAnimated]=useState(true);const[scrolled,setScrolled]=useState(false);const menuRef=useRef<HTMLElement>(null);const menuButton=useRef<HTMLButtonElement>(null);
 useEffect(()=>{const mq=window.matchMedia('(prefers-reduced-motion: reduce)');const saved=localStorage.getItem('studio-motion');setAnimated(saved ? saved==='on':!mq.matches);const timer=setTimeout(()=>setLoading(false),1300);return()=>clearTimeout(timer)},[]);
 useEffect(()=>{if(!animated)return;const lenis=new Lenis({lerp:.09,smoothWheel:true,anchors:true,autoRaf:true});return()=>lenis.destroy()},[animated]);
 useEffect(()=>{const onScroll=()=>setScrolled(window.scrollY>50);onScroll();window.addEventListener('scroll',onScroll,{passive:true});return()=>window.removeEventListener('scroll',onScroll)},[]);
 useEffect(()=>{if(!open)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';menuRef.current?.querySelector('a')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);menuButton.current?.focus()}if(e.key==='Tab'){const links=menuRef.current?.querySelectorAll('a');if(!links?.length)return;const first=links[0],last=links[links.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();menuButton.current?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();menuButton.current?.focus()}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=previous;document.removeEventListener('keydown',key)}},[open]);
 function toggle(){setAnimated(v=>{localStorage.setItem('studio-motion',v?'off':'on');return !v})}
 return <MotionContext.Provider value={animated}><MotionConfig reducedMotion={animated?'user':'always'}><div className={animated?'site motion-on':'site motion-off'}>
 <a href="#main" className="skip-link">Skip to content</a>
 <AnimatePresence>{loading&&<motion.div className="intro-curtain" initial={{y:0}} exit={{y:'-105%',borderRadius:'0 0 40% 40%'}} transition={{duration:.85,ease:[.76,0,.24,1]}} aria-hidden><motion.div initial={{opacity:0,y:35}} animate={{opacity:1,y:0}}><Wordmark/><div className="loader-words"><span>undo the ordinary.</span><span>redo the possibilities.</span></div></motion.div><span className="loader-bottom">GOOD THINKING. GREAT DESIGN.</span></motion.div>}</AnimatePresence>
 <header className={`nav-bar ${scrolled?'scrolled':''}`}><Link href="/" aria-label="Studio Undo/Redo home" onClick={()=>setOpen(false)}><Wordmark/></Link><nav className="desktop-nav" aria-label="Main navigation">{[['/work','Our work'],['/about','The studio'],['/services','What we do']].map(([href,label])=><Link key={href} href={href} aria-current={pathname.startsWith(href)?'page':undefined}>{label}</Link>)}</nav><Link className="nav-contact" href="/contact">Let’s talk <span>↗</span></Link><button ref={menuButton} className="menu-toggle" aria-expanded={open} aria-controls="mobile-menu" onClick={()=>setOpen(!open)}>{open?'Close ✕':'Menu +'}</button></header>
 <AnimatePresence>{open&&<motion.nav ref={menuRef} id="mobile-menu" className="mobile-menu" aria-label="Mobile navigation" initial={{opacity:0,y:-20}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-20}}>{[['/','Home'],['/work','Our work'],['/about','The studio'],['/services','What we do'],['/contact','Let’s talk']].map(([href,label],i)=><Link key={href} href={href} onClick={()=>setOpen(false)}><small>0{i+1}</small>{label}<span>↗</span></Link>)}</motion.nav>}</AnimatePresence>
 <motion.div key={pathname} initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{duration:.55}}>{children}</motion.div>
 <footer className="footer"><div className="footer-top"><span className="eyebrow">THE NEXT GOOD THING STARTS WITH A HELLO</span><span>New Delhi, India ↗ Everywhere</span></div><Link href="/contact" className="footer-title">Your next chapter.<br/><span>Let’s make it <i>pop.</i></span><b>↗</b></Link><div className="footer-mid"><a href="mailto:work@studioundoredo.com">work@studioundoredo.com ↗</a><a href="tel:+918920373342">+91 89203 73342</a><div><a href="https://www.instagram.com/studioundoredo/" target="_blank" rel="noreferrer">Instagram ↗</a><a href="https://www.linkedin.com/company/studioundoredo" target="_blank" rel="noreferrer">LinkedIn ↗</a></div></div><div className="footer-bottom"><Link href="/"><Wordmark/></Link><span>© {new Date().getFullYear()} Studio Undo/Redo</span><button onClick={toggle} aria-pressed={!animated}>{animated?'◉ Motion on':'○ Motion off'}</button></div></footer>
 </div></MotionConfig></MotionContext.Provider>
}
